export const services: string[] = [
  "Plumbing",
  "Electrical services",
  "Satellite dish installations",
  "Solar power installation and maintenance",
  "Smoke detectors and fire alarm system installation",
  "CCTV cameras installation",
  "Automatic doorbell security system",
  "Starlink and internet service systems",
  "Roofing and furniture",
  "Automobile services",
  "Building and construction",
  "Real estate",
  "General merchandise",
  "Security surveillance cameras",
  "Many more",
];
