export const services: string[] = [
    "Wiring and rewiring",
    "Pipe installation and repair",
    "Residential solar panel installation",
    "Electrical panel upgrades",
    "Water heater installation and maintenance",
    "Outlet and switch installation or repair",
    "Drain cleaning and unclogging",
    "Solar system inspection and maintenance",
    "Ceiling fan installation and maintenance",
    "Bathroom and kitchen fixture installation",
    "Solar battery storage installation",
    "Smart home system setup",
    "Leak detection and repair",
    "Inverter installation and replacement",
    "Troubleshooting electrical issues",
    "Gas line installation and repair",
    "Smoke and carbon monoxide detector installation",
    "Solar panel cleaning services",
    "Generator installation and repair",
    "Energy-efficient lighting solutions",
    "Septic system maintenance",
    "Landscape and security lighting",
    "Off-grid solar system setup",
    "Emergency plumbing services",
    "Solar energy consultations",
    "Backflow prevention services",
    "Surge protection installation",
    "EV charger installation",
    "Water filtration system installation",
    "Solar water heater installation",
    "Sewer line repair and replacement",
  ];
  